- hosts: all
  become: yes
  tasks:
    - name: Installing nginx
      apt: name=nginx update_cache=yes
    - name: Starting nginx on boot
      service: name=nginx enabled=yes state=started
    - name: Install git
      apt: pkg=git state=present update_cache=yes
    
    
